#!/usr/bin/env bash
# tranfer file from client to server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	echo "Good"
fi

PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

scp -i $PATH_TO_SSH_KEY $PATH_TO_FILE $USERNAME@$IP:~/ 
