#!/usr/bin/env bash
# echo "Best School 10 time with while loop"

COUNTER=1

while [ "$COUNTER" -le 20 ]
do
	case "$COUNTER" in
		
		4)
		printf "4\nbad luck from China\n"
		;;

		9)
		printf "9\nbad luck from Japan\n"
		;;

		17)
		printf "17\nbad luck from Italy\n"
		;;

		*)
		echo "$COUNTER"

	esac
	
	COUNTER=$((COUNTER+1))
done
