#!/usr/bin/env bash
# echo "displays the time for 12 hours and 59 minutes:"

MINUTE=1
HOUR=0

while [ "$HOUR" -le 12 ]
do
	echo "Hour: $HOUR"
	while [ "$MINUTE" -lt 60 ]
	do
		echo "$MINUTE"
		MINUTE=$((MINUTE+1))
	done
	MINUTE=1
	HOUR=$((HOUR+1))
done
